# Generated by Django 2.2.1 on 2019-05-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('Genre', models.CharField(max_length=255)),
                ('description', models.TextField(default='Descrição')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
