# Generated by Django 2.2.1 on 2019-05-10 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Genre',
            new_name='genre',
        ),
    ]
